---
- hosts: localhost
  connection: local
  become: true


  tasks:
  - name: install stuff
    package:
      name: 
        - htop
        - git
        - tmux
        - zsh
        - docker.io
        - docker-compose