---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install stuff
    package:
      name: 
        - htop
        - git
        - tmux
        - zsh
        - vim-nox
        - python3-psutil
        - jq
        - curl
        - evolution
        - ranger
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - rofi
        - neofetch
        - gnome-tweaks
        - nala

  - name: Install ZSH
    become: true
    ansible.builtin.package:
      name: zsh
      state: present

  - name: Install zoxide
    become: true
    ansible.builtin.package:
      state: present
      name: zoxide
  
  # required by the OMZ plugin zsh-interactive-cd
  - name: Install fzf (command-line fuzzy finder)
    become: true
    ansible.builtin.package:
      state: present
      name: fzf
  
  - name: Install Oh My Zsh # noqa: latest
    ansible.builtin.git:
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: ~/.oh-my-zsh
      depth: 1
  
  - name: Install zsh-autosuggestions plugin # noqa: latest
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      depth: 1
  
  - name: Install zsh-completions plugin # noqa: latest
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-completions
      dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
      depth: 1
  
  - name: Install zsh-syntax-highlighting plugin # noqa: latest
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      depth: 1
  
  - name: Change user shell to zsh 
    become: true
    ansible.builtin.user:
      name: "guye"
      shell: /bin/zsh


  - name: Install VSCode
    snap:
      name: code
      classic: yes

  - name: install python modules
    pip:
      name:
        - psutil
        - requests
        - pandas
        - numpy
        - matplotlib
        - seaborn
        - jupyterlab
        - rich
        - selenium
        - bs4
        - lxml
        - pyyaml

  - name: setup theme
    ansible.builtin.include_tasks:
      file: tasks/theme.yml

  - name: setup ansible-pull cron job
    ansible.builtin.include_tasks:
      file: tasks/ansiblecron.yml

  - name: copy over config files
    ansible.builtin.include_tasks:
      file: tasks/copyconfigs.yml
