---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install stuff
    package:
      name: 
        - htop
        - git
        - tmux
        - zsh
        - vim-nox
        - python3-psutil
        - jq
        - curl
        - evolution
        - ranger
        - docker-ce
        - docker-ce-cli
        - containerd.io

  # - name: Install Oh My Zsh
  #   shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended

  - name: Install VSCode
    snap:
      name: code
      classic: yes

  - name: install python modules
    pip:
      name:
        - psutil
        - requests
        - pandas
        - numpy
        - matplotlib
        - seaborn
        - jupyterlab
        - rich
        - selenium
        - bs4
        - lxml
        - pyyaml

  - name: copy .bashrc file
    copy:
      src: files/.bashrc
      dest: /home/guye/.bashrc
      owner: guye
      group: guye

  - name: copy .zshrc file
    copy:
      src: files/.zshrc
      dest: /home/guye/.zshrc
      owner: guye
      group: guye

  - name: add ansible user
    user:
      name: velociraptor
      system: yes

  - name: setup sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440
  
  - name: add ansible-pull cron job
    cron:
      name: ansible-pull
      user: velociraptor
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/00SecretSQRL/ansible_desktop.git

  - name: setup theme
    ansible.builtin.include_tasks:
      file: tasks/theme.yml
