---
  - name: add ansible user
    user:
      name: velociraptor
      system: yes

  - name: setup sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440
  
  - name: add ansible-pull cron job
    cron:
      name: ansible-pull
      user: velociraptor
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/00SecretSQRL/ansible_desktop.git

