---
  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: guye
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: guye
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: unzip dracula theme
    unarchive:
      src: files/gtk-dracula.zip
      dest: /usr/share/themes/
  
  - name: set dracula theme
    become_user: guye
    dconf:
      key: "/org/gnome/desktop/interface/gtk-theme"
      value: "'gtk-master'"